### ISSUE TITLE
Make cursor change on brick hover.

### ISSUE THREAD

**Issue by michaelplzno** [michaelplzno/Blokaroka#10]
When the mouse is hovering a brick it still has the cursor for whatever is underneath. So if you are on a text box it is still the text vertical bar cursor.

We need to make it so you get the finger hand whenever the mouse is on top of a brick, this one is a pretty easy one.

**Comment by atomikjaye** [comment]
I would like to attempt this is that's alright

**Comment by michaelplzno** [comment]
Sounds good! I added you as a collaborator. Make a pull request when you figure it out and msg me if you have questions. 

Good luck!

**Comment by atomikjaye** [comment]
Just submitted PR #15 for cursor fix.

**Comment by atomikjaye** [comment]
Just got the okay and wanted to update with the awesome person who helped tremendously! @dmry
