### ISSUE TITLE
Prevent multiple instances.

### ISSUE THREAD

**Issue by michaelplzno** [michaelplzno/Blokaroka#16]
We need to make sure only one version of the program is running at a time or there is unexpected results. I know some programs have a way of doing this so it can be done, I just don't know how.

**Comment by RafeeqShodeinde** [comment]
I will like to work on this issue!
This is my first time contributing to a github project so please bare with me haha

I have a mac book now, Is it okay for me to download visual studio on it and work and test my potential .exe file on a windows laptop??

I guess I have a couple of questions:
1. Where is the instance of the game application being created?? is it in Blokaroka.cpp or is it in Renderer.cpp in the InitRenderer method??
2. I have created a fork to this repo, but how do I test that my code changes actually work. In short how do i get an updated Blokaroka.exe file after I change the code?
3. What is the use of the Renderer.cpp & .h file so I'm sure I have the right idea?

**Comment by michaelplzno** [comment]
Hi Rafeeq! 

As of now you will need a PC to run the code, so a Windows laptop should work fine for that. Just download Visual Studio and load up the project and it should compile and run. The latest compiled .exe are downloadable at [https://blokaroka.com](https://blokaroka.com) so if you want to see what the correct version looks like try downloading it from there.

1) Blokaroka.cpp contains the main function that is called by Windows and loops and calls other functions but it calls the function Renderer::InitRenderer which is where the actual application window is created.

2) To get an updated EXE you have to build the code you write on your local machine with visual studio. This will create a new EXE that you can test and also debug for errors.

3) The .h file for any code in the project contains header information and declares the functions and variables that class will use. For the Renderer.h it declares drawing and rendering functions. The Renderer.cpp file contains all the code for interacting with windows, creating the window and also drawing the bricks. 

Let me know if you have any more questions!

**Comment by michaelplzno** [comment]
Great work Rafeeq!
